version: "3"
services:
    app:
        build:
            context: ../../go
        container_name: app
        env_file:
            - .env
        # tty: true # 永続化
        ports:
            - ${PORT}:${PORT}
        volumes:
            - type: bind
              source: ./log
              target: /api/log
            - type: bind
              source: ./gcloud.json
              target: /api/gcloud.json
