version: "3"
services:
    app:
        build:
            context: ../../go
        container_name: app
        env_file:
            - .env
        # tty: true # 永続化
        ports:
            - ${PORT}:${PORT}
        volumes:
            - type: bind
              source: ./log/go.log
              target: /api/go/debug.log
            - type: bind
              source: ~/service-key/vision-api.json
              target: /vision-api.json