name: CD to EC2

on:
    pull_request:
        branches: [main]
        types: [closed]

    workflow_dispatch:

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_IAM_CREDENTIALS }}'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: 'instance-main-1'
        zone: 'us-west1-b'
        user: 'tattet'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: |-
          cd /home/tattet/narcissus/docker/cloud-build
          docker compose down
          git pull
          docker compose build
          docker compose up -d

    # Example of using the output
    - id: 'output-test'
      run: |-
        echo '${{ steps.compute-ssh.outputs.stdout }}'
        echo '${{ steps.compute-ssh.outputs.stderr }}'